# Generated by Django 6.0.3 on 2026-05-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listing_options_remove_listing_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('booked', 'Забронировано'), ('archived', 'Архивировано')], default='active', max_length=10, verbose_name='Статус'),
        ),
    ]
